---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      name: hello
      labels:
        app: hello
    spec:
      containers:
      - name: hello
        image: penmetsa29/hello:v1
        ports:
        - name: hello
          containerPort: 8080
        resources:
          limits:
            memory: "2Gi"
            cpu: "1000m"
          requests:
            memory: "1Gi"
            cpu: "500m"
      volumes:
        - name: hello-config
          configMap:
              defaultMode: 420
              name: hello-config
