---
apiVersion: v1
kind: Service
metadata:
  name: hello
  namespace: monitoring
spec:
  selector:
    app: hello
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31000
